<?php

/**
 * @file
 * Provides password controls, validation, and strength checker.
 */

/**
 * Implements hook_xautoload().
 */
function password_strength_xautoload($api) {
  $api->namespaceRoot('ZxcvbnPhp', 'lib/zxcvbn-php/src');
}

/**
 * Implements hook_menu().
 */
function password_strength_menu() {
  $items = array();
  $items['system/password-strength-check'] = array(
    'title' => 'Check password',
    'page callback' => 'password_strength_ajax_check',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/system/password-strength'] = array(
    'title' => 'Password Strength settings',
    'description' => 'Manage password strength settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('password_strength_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'password_strength.admin.inc',
    'weight' => 20,
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function password_strength_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_register_form':
      // Include password strength JS check and validation handler.
      password_strength_form_password_add($form['account']['pass'], $form);
      break;
    case 'user_profile_form':
      global $user;
      password_strength_form_password_add($form['account']['pass'], $form, $user);
      break;
  }
}

/**
 * Implements hook_element_info_alter().
 */
function password_strength_element_info_alter(&$types) {
  // Remove user_form_process_password_confirm process callback from
  // password_confirm element. This will remove the password strength
  // checker on password fields.
  if (isset($types['password_confirm']['#process'])) {
    $process = 'user_form_process_password_confirm';
    if (($position = array_search($process, $types['password_confirm']['#process'])) !== FALSE) {
      unset($types['password_confirm']['#process'][$position]);
    }
  }
}

/**
 * Form extensions for password strength controls.
 *
 * @param array &$element
 * @param array &$form
 * @param $account
 */
function password_strength_form_password_add(&$element, &$form, $account = NULL) {
  $js_settings = array();
  $key = 'password_strength';

  // The default required password score can be provided as a URL parameter.
  $default_required_score = isset($_GET['password_score']) ? $_GET['password_score'] : NULL;
  if (!is_null($account)) {
    $score = password_strength_required_score($account, $default_required_score);
    $js_settings['policy_score'] = $score;
    $key .= ':' . $account->uid;
  }
  $js_settings['token'] = drupal_get_token($key);
  $js_settings['secure_base_url'] = url(NULL, array('absolute' => TRUE, 'https' => TRUE, 'purl' => array('disabled' => TRUE)));

  // If a password score was provided via URL, store the value in form so it can
  // be used in the validation/submit handlers.
  if (isset($default_required_score)) {
    $form['password_score'] = array('#type' => 'value', '#value' => $default_required_score);
  }

  // Attach password strength check JS.
  $element['#attached']['css'][] = drupal_get_path('module', 'password_strength') . '/css/password.css';
  $element['#attached']['js'][] = array(
    'data' => array('passwordStrength' => $js_settings),
    'type' => 'setting',
  );
  $element['#attached']['js'][] = array(
    'data' => drupal_get_path('module', 'password_strength') . '/js/password.js',
    'weight' => 10,
  );

  $form['#validate'][] = 'password_strength_form_password_validate';
  // Run password_submit handler before others.
  $form['#submit'] = array_merge(array('password_strength_form_password_submit'),  $form['#submit']);
}

/**
 * Validation handler for password field.
 */
function password_strength_form_password_validate($form, &$form_state) {
  global $user;
  $account = NULL;
  if (isset($form['#user'])) {
    $account = $form["#user"];
  }
  else {
    $account = $user;
  }
  $default_required_score = isset($form_state['values']['password_score']) ? $form_state['values']['password_score'] : NULL;
  $required_score = password_strength_required_score($account, $default_required_score);
  $pass = $form_state['values']['pass'];
  $strength = password_strength_strength($pass, $account, $default_required_score);

  // Only validate if score is required to be above 0.
  if ($required_score && $strength['score'] < $required_score) {
    form_set_error('pass', t("Password does not meet required strength"));
  }
  elseif (!empty($strength['matches'])) {
    // @todo remove these in favor of password policy rules
    foreach ($strength['matches'] as $match) {
      if ($match['pattern'] == 'name') {
        form_set_error('pass', t("Password cannot match your account name"));
        break;
      }
      elseif ($match['pattern'] == 'mail') {
        form_set_error('pass', t("Password cannot match your account email address"));
        break;
      }
    }
  }
}

/**
 * Submission handler for password field.
 */
function password_strength_form_password_submit($form, &$form_state) {
  // Password has passed validation. Save strength and report change.
  global $user;
  if (isset($form['#user'])) {
    $account = $form["#user"];
  }
  else {
    $account = $user;
  }

  $default_required_score = isset($form_state['values']['password_score']) ? $form_state['values']['password_score'] : NULL;
  $pass = $form_state['values']['pass'];
  $strength = password_strength_strength($pass, $account, $default_required_score);

  // Invoke password_strength_change hook.
  module_invoke_all('password_strength_change', $account, $strength);
}

/**
 * Menu callback for AJAX password check.
 */
function password_strength_ajax_check() {
  global $user;

  // Prevent this page from being cached.
  drupal_page_is_cacheable(FALSE);

  $password = $_POST['password'];
  if (!isset($_POST['token'])) {
    drupal_json_output(FALSE);
    return;
  }
  // Disallow POSTs larger than 256 characters as minor protection against DOS.
  if (strlen($password) > 256) {
    drupal_json_output(FALSE);
    return;
  }
  $account = NULL;
  $key = 'password_strength';
  if ($user->uid > 0) {
    // Provide account as context for password strength.
    $account = $user;
    $key .= ':' . $account->uid;
  }
  // @todo: fix validation for anonymous users.
  // Validate token.
  // if (!drupal_valid_token($_POST['token'], $key)) {
  //   drupal_json_output(FALSE);
  //   return;
  // }

  // Get strength information from the password checker library.
  $default_required_score = isset($_REQUEST['password_score']) ? $_REQUEST['password_score'] : NULL;
  $strength = password_strength_strength($password, $account, $default_required_score);

  // Get messages.
  $message_strength = password_strength_get_message_strength($strength);
  $message_flaws = password_strength_get_message_flaws($strength);

  // Here or password_strength_strength() may need to do zxcvbn() format
  // manipulation @todo
  $data = array(
    'entropy' => $strength['entropy'],
    'matches' => $strength['matches'],
    'score' => $strength['score'],
    'score_required' => $strength['score_required'],
    'percent' => $strength['percent'],
    'message_strength' => drupal_render($message_strength),
    'message_requirements' => '',
    'message_flaws' => drupal_render($message_flaws),
  );

  drupal_json_output($data);
}

/**
 * Gets Zxcvbn entropy and score for a password.
 *
 * @param string $password
 *   Plain-text password to be measured.
 *
 * @param stdClass $account
 *   Optional Drupal user account for additional contexts.
 *
 * @param int $default_required_score
 *   Optional default minimum required score. If none is provided
 *   min score is determined from 'password_strength_default_required_score'
 *   variable.
 *
 * @return array
 *   Result array with keys:
 *     entropy - float
 *     score - int
 *     match_sequence - Array of Match objects from ZxcvbnPhp
 *     matches - Array with arrays of pattern data deduced from match_sequence
 *     percent - float
 */
function password_strength_strength($password, $account = NULL, $default_required_score = NULL) {
  global $user;

  if (empty($account)) {
    $account = $user;
  }

  // Get the required score needed for this account.
  $score_required = password_strength_required_score($account, $default_required_score);

  // Return early if password matches email or account name.
  $strength = array(
    'entropy' => 0,
    'score' => 0,
    'score_required' => $score_required,
    'percent' => 0,
    'match_sequence' => array(),
    'matches' => array(),
  );

  // Add a length matcher to add a message if the password
  // is less then 7 characters.
  if (strlen($password) < variable_get('password_strength_default_password_length', 7)) {
    $strength['matches'][] = array(
      'pattern' => 'length',
      'matched' => $password,
    );
    return $strength;
  }

  if (strtolower(trim(urldecode($password))) == $account->mail) {
    $strength['matches'][] = array(
      'pattern' => 'mail',
      'matched' => $password,
    );
    return $strength;
  }

  if (strtolower(trim(urldecode($password))) == $account->name) {
    $strength['matches'][] = array(
      'pattern' => 'name',
      'matched' => $password,
    );
    return $strength;
  }

  // Get password strength information from Zxcvbn.
  $zxcvbn                     = new ZxcvbnPhp\Zxcvbn();
  $strength                   = $zxcvbn->passwordStrength($password);
  $strength['score_required'] = $score_required;
  $strength['matches']        = array();

  // Determine which match sequences we can use to help the user
  // on the front end when choosing a password. Filter out some
  // of the stuff that wouldn't really make sense to the user.
  foreach ($strength['match_sequence'] as $match) {

    // Ignore patterns whose tokens are less then 3 characters,
    // they're not very useful to show the user.
    if (strlen($match->token) < 3) {
      continue;
    }

    $strength['matches'][] = array(
      'pattern' => password_strength_strength_pattern($match),
      'matched' => $match->token,
    );

  }

  // Calculate a percentage of the score based on the required score. This will be
  // used to animate a strength bar on the front end. Make sure this value is between
  // 0 and 100.
  if ($strength['score_required'] != 0) {
    $strength['percent'] = round($strength['score'] / $strength['score_required'] * 100);
  }
  else {
    $strength['percent'] = round($strength['score'] / 4 * 100);
  }

  $strength['percent'] = ($strength['percent'] >= 0) ? $strength['percent'] : 0;
  $strength['percent'] = ($strength['percent'] <= 100) ? $strength['percent'] : 100;

  // Pass user account properties into checker.

  return $strength;
}

/**
 * Determines the flaw pattern from the match object.
 *
 * This is an internal key that the module will use when displaying
 * the flaws found in the password.
 *
 * @param object $match
 *   An match object.
 *
 * @return string
 *   An internal pattern identifier.
 *
 */
function password_strength_strength_pattern($match) {
  if (isset($match->l33t) && $match->l33t) {
    $pattern = 'leetspeak';
  }
  else {
    $pattern = $match->pattern;
  }

  return $pattern;
}

/**
 * Returns a human readable list of score levels.
 *
 * @return array
 *   A list of human readable score levels.
 *
 */
function password_strength_score_list() {
  return array(
    t('very weak'),
    t('weak'),
    t('good'),
    t('strong'),
    t('very strong'),
  );
}

/**
 * Returns a human readable version of the password score.
 *
 * @param int $score
 *   An integer corresponding to a password strength.
 *
 * @return string
 *   A human readable version of the score.
 *
 */
function password_strength_get_score($score) {
  $scores = password_strength_score_list();
  return isset($scores[$score]) ? $scores[$score] : t('unknown');
}

/**
 * Returns helper strength indicator for password strength.
 *
 * @param array $strength
 *   An array containing password strength details.
 *
 * @return array
 *   A render array containing password strength markup.
 *
 */
function password_strength_get_message_strength($strength) {
  $score = password_strength_get_score($strength['score']);

  $build = array();
  $build['content'] = array(
    '#markup' => ''
      . '<div class="name">' . t('Password strength:') . '</div> '
      . '<div class="value text-score-' . $strength['score'] . '">' . $score . '</div>',
  );

  return $build;
}

/**
 * Returns helper message for password strength.
 *
 * @param array $strength
 *   An array containing password strength details.
 *
 * @return array
 *   A render array.
 *
 */
function password_strength_get_message_flaws($strength) {
  $flaws = password_strength_get_flaws($strength);

  $build = array();

  if (!empty($flaws)) {
    $build['intro'] = array(
      '#markup' => '<p>' . t('The following issues were detected with your password:') . '</p>',
    );
    $build['flaws'] = array(
      '#theme' => 'item_list',
      '#items' => $flaws,
    );
  }

  return $build;
}

/**
 * Returns an array of flaws found in the password strength.
 *
 * @param array $strength
 *   An array containing password strength details.
 *
 * @return array
 *
 */
function password_strength_get_flaws($strength) {
  $use_eg = TRUE;
  $use_eg_live = FALSE;
  $use_eg_live_attr = FALSE;

  $flaws = array(
    'length' => array(
      'text' => t('Is shorter than 7 characters'),
      'examples' => NULL,
    ),
    'mail' => array(
      'text' => t('Matches your email address'),
      'examples' => NULL,
    ),
    'name' => array(
      'text' => t('Matches your account name'),
      'examples' => NULL,
    ),
    'dictionary' => array(
      'text' => t('Contains dictionary words'),
      'examples' => array('password'),
    ),
    'sequence' => array(
      'text' => t('Has a common character sequence'),
      'examples' => array('12345', 'abc'),
    ),
    'repeat' => array(
      'text' => t('Includes repeated characters'),
      'examples' => array('aaa', '55555'),
    ),
    'leetspeak' => array(
      'text' => t('Has leet (or “1337”), also known as eleet or leetspeak'),
      'examples' => array('p4ssw0rd'),
    ),
    'spatial' => array(
      'text' => t('Has a keyboard sequence'),
      'examples' => array('qwerty', 'asdf'),
    ),
    'digit' => array(
      'text' => t('Has a series of just digits'),
      'examples' => array('929'),
    ),
    'date' => array(
      'text' => t('Includes a date'),
      'examples' => array('19-11-1978'),
    ),
    'year' => array(
      'text' => t('Includes a year'),
      'examples' => array('2013'),
    ),
  );

  // Collect all matched patterns.
  $matches = array();
  foreach ($strength['matches'] as $match) {
    $matches[$match['pattern']][] = $match['matched'];
  }

  // Build a list of flaws for this password.
  $items = array();
  foreach ($matches as $pattern => $match) {
    if (!isset($flaws[$pattern])) {
      continue;
    }

    $flaw = $flaws[$pattern];
    $item = array();
    $item['data'] = $flaw['text'];

    // Use default examples.
    if ($use_eg && !empty($flaw['text']) && !empty($flaw['examples'])) {
      $item['data'] .= t(' (e.g. "@match")', array('@match' => implode('", "', $flaw['examples'])));
    }

    // Use live examples.
    if ($use_eg_live) {
      $item['data'] .= t(' (e.g. "@match")', array('@match' => implode('", "', $match)));
    }

    // Use live examples in title attributes.
    if ($use_eg_live_attr) {
      $hint = t('e.g. @match', array('@match' => implode(', ', $match)));
      $item['data'] .= ' (<span class="hint" title="' . $hint . '">?</span>)';
    }

    $items[] = $item;
  }

  return $items;
}

/**
 * Gets the Zxcvbn password score required for an account.
 *
 * @param stdClass $account
 *   Drupal user account.
 *
 * @param int $default_required_score
 *   Optional default minimum required score. If none is provided
 *   min score is determiend from 'password_strength_default_required_score'
 *   variable.
 *
 * @return int
 *   Minimum password score required.
 */
function password_strength_required_score($account, $default_required_score = NULL) {
  // Determine what is the default minimum score for account.
  $score = isset($default_required_score) ? $default_required_score : variable_get('password_strength_default_required_score', 0);

  // Anonymous users are required to have the default minimum score.
  if ($account->uid == 0) {
    return $score;
  }
  // @todo hook for higher required strengths
  return $score;
}
